USE bkp_db_uc_kami;
select 
cliente.cod_cliente as cod_cliente
,cliente.razao_social as razao_social
,cliente.nome_cliente as nome_cliente
,max(ramo.desc_abrev) as tipo
,DATE_FORMAT(cliente.dt_implant,'%d/%m/%Y') as data_cadastro
,endereco.bairro as bairro
,endereco.cidade as cidade
,endereco.endereco as endereco
,endereco.numero as numero
,endereco.cep as cep
,cliente.cod_colaborador as cod_vendedor
,vendedor.nome_colaborador as nome_vendedor
,(select  CASE WHEN (sum(recebe.vl_total_titulo) - sum(recebe.vl_total_baixa)) > 0 THEN  ( TIMESTAMPDIFF(DAY,recebe.dt_vencimento, CURRENT_DATE()))  
ELSE  "0" END from fn_titulo_receber as recebe where recebe.cod_cliente = cliente.cod_cliente and recebe.situacao < 30 and recebe.dt_vencimento < CURRENT_DATE() -1  and recebe.cod_empresa in (1,3)  group by recebe.cod_cliente) as dias_atraso
,(select CASE WHEN (sum(recebe.vl_total_titulo) - sum(recebe.vl_total_baixa)) > 0 THEN  (sum(recebe.vl_total_titulo) - sum(recebe.vl_total_baixa))  
ELSE  "0" END from fn_titulo_receber as recebe where recebe.cod_cliente = cliente.cod_cliente and recebe.situacao < 30 and recebe.dt_vencimento < CURRENT_DATE() -1  and recebe.cod_empresa in (1,3) group by recebe.cod_cliente) as valor_devido

,(select DATE_FORMAT(max(nf2.dt_emissao),'%d/%m/%Y') from vd_nota_fiscal as nf2 where cliente.cod_cliente = nf2.cod_cliente and nf2.situacao < 81 and nf2.cod_empresa in (1,3) and nf2.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dt_ultima_compra

,(select DATE_FORMAT(min(nf2.dt_emissao),'%d/%m/%Y') from vd_nota_fiscal as nf2 where cliente.cod_cliente = nf2.cod_cliente and nf2.situacao < 81 and nf2.cod_empresa in (1,3) and nf2.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dt_primeira_compra

,(select count(distinct nf2.dt_emissao) from vd_nota_fiscal as nf2 where cliente.cod_cliente = nf2.cod_cliente and nf2.situacao < 81 and nf2.cod_empresa in (1,3) and nf2.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as qtd_total_compras

,(select count(distinct nf2.dt_emissao) from vd_nota_fiscal as nf2 where cliente.cod_cliente = nf2.cod_cliente and nf2.situacao < 81 and nf2.cod_empresa in (1,3) and nf2.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP") and nf2.dt_emissao >= SUBDATE(CURDATE(), INTERVAL 6 MONTH)) as qtd_compras_semestre

,(select TIMESTAMPDIFF(DAY,max(nf2.dt_emissao),CURRENT_DATE() ) from vd_nota_fiscal as nf2 where cliente.cod_cliente = nf2.cod_cliente and nf2.situacao < 81 and nf2.cod_empresa in (1,3)) as dias_sem_compra

,recebe.sigla_uf as uf

,ramo.desc_abrev as classificacao

#janeiro 2020 
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as janeiro_2020
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as janeiro_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as janeiro_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as janeiro_2020_ENXOVAL

#janeiro 2021
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as janeiro_2021
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as janeiro_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as janeiro_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as janeiro_2021_ENXOVAL

#janeiro 2022
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as janeiro_2022
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as janeiro_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as janeiro_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (1) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as janeiro_2022_ENXOVAL

#fevereiro 2020
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as fevereiro_2020
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as fevereiro_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as fevereiro_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as fevereiro_2020_ENXOVAL


#fevereiro 2021
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as fevereiro_2021
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as fevereiro_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as fevereiro_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as fevereiro_2021_ENXOVAL

#fevereiro 2022
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as fevereiro_2022
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as fevereiro_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as fevereiro_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (2) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as fevereiro_2022_ENXOVAL

#marco 2020
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as marco_2020
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as marco_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as marco_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as marco_2020_ENXOVAL

#marco 2021
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as marco_2021
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as marco_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as marco_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as marco_2021_ENXOVAL

#marco 2022
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as marco_2022
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as marco_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as marco_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (3) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as marco_2022_ENXOVAL

#abril 2020
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as abril_2020
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as abril_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as abril_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as abril_2020_ENXOVAL

#abril 2021
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as abril_2021
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as abril_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as abril_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as abril_2021_ENXOVAL

#abril 2022
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as abril_2022
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as abril_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as abril_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (4) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as abril_2022_ENXOVAL

#maio 2020
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as maio_2020
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as maio_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as maio_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as maio_2020_ENXOVAL

#maio 2021
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as maio_2021
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as maio_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as maio_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as maio_2021_ENXOVAL

#maio 2022
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as maio_2022
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as maio_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as maio_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (5) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as maio_2022_ENXOVAL

#junho 2020
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as junho_2020
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as junho_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as junho_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as junho_2020_ENXOVAL

#junho 2021
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as junho_2021
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as junho_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as junho_2021_bonifico
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as junho_2021_ENXOVAL

#junho 2022
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as junho_2022
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as junho_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as junho_2023_bonificado
,(select  sum(case when month(nf.dt_emissao) in (6) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as junho_2022_ENXOVAL

#junho 2020
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as julho_2020
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as julho_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as julho_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as julho_2020_ENXOVAL

#junho 2021
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as julho_2021
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as julho_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as julho_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as julho_2021_ENXOVAL

#junho 2022
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as julho_2022
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as julho_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as julho_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (7) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as julho_2022_ENXOVAL

#agosto 2020
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as agosto_2020
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as agosto_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as agosto_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as agosto_2020_ENXOVAL

#agosto 2021
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as agosto_2021
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as agosto_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as agosto_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as agosto_2021_ENXOVAL

#agosto 2022
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as agosto_2022
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as agosto_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as agosto_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (8) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as agosto_2022_ENXOVAL

#setembro 2020
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as setembro_2020
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as setembro_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as setembro_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as setembro_2020_ENXOVAL

#setembro 2021
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as setembro_2021
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as setembro_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as setembro_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as setembro_2021_ENXOVAL

#setembro 2022
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as setembro_2022
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as setembro_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as setembro_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (9) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as setembro_2022_ENXOVAL

#outubro 2020
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as outrubo_2020
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as outrubo_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as outrubo_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as outrubo_2020_ENXOVAL

#outubro 2021
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as outrubo_2021
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as outrubo_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as outrubo_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as outrubo_2021_ENXOVAL

#outubro 2022
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as outrubo_2022
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as outrubo_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as outrubo_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (10) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as outrubo_2022_ENXOVAL

#novembro 2020
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as novembro_2020
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as novembro_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as novembro_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as novembro_2020_ENXOVAL

#novembro 2021
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as novembro_2021
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as novembro_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as novembro_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as novembro_2021_ENXOVAL

#novembro 2022
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as novembro_2022
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as novembro_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as novembro_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (11) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as novembro_2022_ENXOVAL


#dezembro 2020
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dezembro_2020
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dezembro_2020_desconto
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as dezembro_2020_bonificado
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2020-01-01" and nf.dt_emissao < "2021-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as dezembro_2020_ENXOVAL

#dezembro 2021
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dezembro_2021
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dezembro_2021_desconto
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as dezembro_2021_bonificado
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2021-01-01" and nf.dt_emissao < "2022-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as dezembro_2021_ENXOVAL

#dezembro 2022
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dezembro_2022
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull(((nf.vl_total_tb_kami - nf.vl_total_nota_fiscal)),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("6.102","6.404","BLACKFRIDAY","VENDA","VENDA_S_ESTOQUE","WORKSHOP")) as dezembro_2022_desconto
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("BONIFICADO", "BONIFICADO_F","BONI_COMPRA","PROMOCAO","PROMO_BLACK","CAMPANHA")) as dezembro_2022_bonificado
,(select  sum(case when month(nf.dt_emissao) in (12) then ifnull((nf.vl_total_liquido),0) else 0 end) from  vd_nota_fiscal as nf where  cliente.cod_cliente = nf.cod_cliente and nf.dt_emissao >= "2022-01-01" and nf.dt_emissao < "2023-01-01"  and nf.situacao < 100 and nf.cod_empresa in (1,3) and nf.nop in ("ENXOVAL")) as dezembro_2022_ENXOVAL

from
cd_cliente as cliente
left join cd_cliente_endereco as endereco on (cliente.cod_cliente = endereco.cod_cliente and endereco.tp_endereco = "E")
left join sg_colaborador as vendedor on (vendedor.cod_colaborador = cliente.cod_colaborador )
left join fn_titulo_receber as recebe on (recebe.cod_cliente = cliente.cod_cliente and recebe.situacao < 31 and recebe.cod_empresa in (1,3))
left join cd_cliente_atividade as atividade on(atividade.cod_cliente = cliente.cod_cliente)
left join cd_ramo_atividade as ramo on (ramo.cod_ramo_atividade = atividade.cod_ramo_atividade)

where

 cliente.cod_colaborador in (6,14,17,27,43,53,58,63,77,78,153,171,215,222,251,45)
group by  cliente.cod_cliente


#select DATE_FORMAT(dt_emissao,'%d/%m/%Y'), dt_emissao from vd_nota_fiscal where cod_nota_fiscal = 21707

INTO OUTFILE 'csv/mestres_varejo.csv'
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'